// Generated by gencpp from file turtle_driver/circleRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_DRIVER_MESSAGE_CIRCLEREQUEST_H
#define TURTLE_DRIVER_MESSAGE_CIRCLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_driver
{
template <class ContainerAllocator>
struct circleRequest_
{
  typedef circleRequest_<ContainerAllocator> Type;

  circleRequest_()
    : r(0.0)  {
    }
  circleRequest_(const ContainerAllocator& _alloc)
    : r(0.0)  {
  (void)_alloc;
    }



   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::turtle_driver::circleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_driver::circleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct circleRequest_

typedef ::turtle_driver::circleRequest_<std::allocator<void> > circleRequest;

typedef boost::shared_ptr< ::turtle_driver::circleRequest > circleRequestPtr;
typedef boost::shared_ptr< ::turtle_driver::circleRequest const> circleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_driver::circleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_driver::circleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_driver::circleRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::circleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_driver::circleRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::circleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::circleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::circleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::circleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::circleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::circleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::circleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_driver::circleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "368c8aa4d43e75677f910f4c10899d4c";
  }

  static const char* value(const ::turtle_driver::circleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x368c8aa4d43e7567ULL;
  static const uint64_t static_value2 = 0x7f910f4c10899d4cULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_driver::circleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_driver/circleRequest";
  }

  static const char* value(const ::turtle_driver::circleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_driver::circleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n"
;
  }

  static const char* value(const ::turtle_driver::circleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_driver::circleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct circleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_driver::circleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_driver::circleRequest_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_DRIVER_MESSAGE_CIRCLEREQUEST_H
