// Generated by gencpp from file turtle_driver/customResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_DRIVER_MESSAGE_CUSTOMRESPONSE_H
#define TURTLE_DRIVER_MESSAGE_CUSTOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_driver
{
template <class ContainerAllocator>
struct customResponse_
{
  typedef customResponse_<ContainerAllocator> Type;

  customResponse_()
    : response(0)  {
    }
  customResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int32_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::turtle_driver::customResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_driver::customResponse_<ContainerAllocator> const> ConstPtr;

}; // struct customResponse_

typedef ::turtle_driver::customResponse_<std::allocator<void> > customResponse;

typedef boost::shared_ptr< ::turtle_driver::customResponse > customResponsePtr;
typedef boost::shared_ptr< ::turtle_driver::customResponse const> customResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_driver::customResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_driver::customResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_driver::customResponse_<ContainerAllocator1> & lhs, const ::turtle_driver::customResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_driver::customResponse_<ContainerAllocator1> & lhs, const ::turtle_driver::customResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::customResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::customResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::customResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::customResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::customResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::customResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_driver::customResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f45f68e2feefb1307598e828e260b7d7";
  }

  static const char* value(const ::turtle_driver::customResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf45f68e2feefb130ULL;
  static const uint64_t static_value2 = 0x7598e828e260b7d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_driver::customResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_driver/customResponse";
  }

  static const char* value(const ::turtle_driver::customResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_driver::customResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 response\n"
;
  }

  static const char* value(const ::turtle_driver::customResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_driver::customResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_driver::customResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_driver::customResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int32_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_DRIVER_MESSAGE_CUSTOMRESPONSE_H
