// Generated by gencpp from file turtle_driver/custom.msg
// DO NOT EDIT!


#ifndef TURTLE_DRIVER_MESSAGE_CUSTOM_H
#define TURTLE_DRIVER_MESSAGE_CUSTOM_H

#include <ros/service_traits.h>


#include <turtle_driver/customRequest.h>
#include <turtle_driver/customResponse.h>


namespace turtle_driver
{

struct custom
{

typedef customRequest Request;
typedef customResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct custom
} // namespace turtle_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_driver::custom > {
  static const char* value()
  {
    return "f30909cab7568c3cd2dc3063c407d24a";
  }

  static const char* value(const ::turtle_driver::custom&) { return value(); }
};

template<>
struct DataType< ::turtle_driver::custom > {
  static const char* value()
  {
    return "turtle_driver/custom";
  }

  static const char* value(const ::turtle_driver::custom&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_driver::customRequest> should match
// service_traits::MD5Sum< ::turtle_driver::custom >
template<>
struct MD5Sum< ::turtle_driver::customRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_driver::custom >::value();
  }
  static const char* value(const ::turtle_driver::customRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_driver::customRequest> should match
// service_traits::DataType< ::turtle_driver::custom >
template<>
struct DataType< ::turtle_driver::customRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_driver::custom >::value();
  }
  static const char* value(const ::turtle_driver::customRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_driver::customResponse> should match
// service_traits::MD5Sum< ::turtle_driver::custom >
template<>
struct MD5Sum< ::turtle_driver::customResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_driver::custom >::value();
  }
  static const char* value(const ::turtle_driver::customResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_driver::customResponse> should match
// service_traits::DataType< ::turtle_driver::custom >
template<>
struct DataType< ::turtle_driver::customResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_driver::custom >::value();
  }
  static const char* value(const ::turtle_driver::customResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_DRIVER_MESSAGE_CUSTOM_H
