// Generated by gencpp from file turtle_driver/customRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_DRIVER_MESSAGE_CUSTOMREQUEST_H
#define TURTLE_DRIVER_MESSAGE_CUSTOMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_driver
{
template <class ContainerAllocator>
struct customRequest_
{
  typedef customRequest_<ContainerAllocator> Type;

  customRequest_()
    : x()
    , y()  {
    }
  customRequest_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::turtle_driver::customRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_driver::customRequest_<ContainerAllocator> const> ConstPtr;

}; // struct customRequest_

typedef ::turtle_driver::customRequest_<std::allocator<void> > customRequest;

typedef boost::shared_ptr< ::turtle_driver::customRequest > customRequestPtr;
typedef boost::shared_ptr< ::turtle_driver::customRequest const> customRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_driver::customRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_driver::customRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_driver::customRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::customRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_driver::customRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::customRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::customRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::customRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::customRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::customRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::customRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::customRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_driver::customRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "462ac0ba687f22c2e73c0ec0413e0202";
  }

  static const char* value(const ::turtle_driver::customRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x462ac0ba687f22c2ULL;
  static const uint64_t static_value2 = 0xe73c0ec0413e0202ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_driver::customRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_driver/customRequest";
  }

  static const char* value(const ::turtle_driver::customRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_driver::customRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n"
"float32[] y\n"
;
  }

  static const char* value(const ::turtle_driver::customRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_driver::customRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_driver::customRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_driver::customRequest_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_DRIVER_MESSAGE_CUSTOMREQUEST_H
