// Generated by gencpp from file turtle_driver/squareRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_DRIVER_MESSAGE_SQUAREREQUEST_H
#define TURTLE_DRIVER_MESSAGE_SQUAREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_driver
{
template <class ContainerAllocator>
struct squareRequest_
{
  typedef squareRequest_<ContainerAllocator> Type;

  squareRequest_()
    : s(0.0)  {
    }
  squareRequest_(const ContainerAllocator& _alloc)
    : s(0.0)  {
  (void)_alloc;
    }



   typedef double _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::turtle_driver::squareRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_driver::squareRequest_<ContainerAllocator> const> ConstPtr;

}; // struct squareRequest_

typedef ::turtle_driver::squareRequest_<std::allocator<void> > squareRequest;

typedef boost::shared_ptr< ::turtle_driver::squareRequest > squareRequestPtr;
typedef boost::shared_ptr< ::turtle_driver::squareRequest const> squareRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_driver::squareRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_driver::squareRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_driver::squareRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::squareRequest_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_driver::squareRequest_<ContainerAllocator1> & lhs, const ::turtle_driver::squareRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::squareRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_driver::squareRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::squareRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_driver::squareRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::squareRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_driver::squareRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_driver::squareRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63117583c3ceae63ea2c1910b9db9c41";
  }

  static const char* value(const ::turtle_driver::squareRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63117583c3ceae63ULL;
  static const uint64_t static_value2 = 0xea2c1910b9db9c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_driver::squareRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_driver/squareRequest";
  }

  static const char* value(const ::turtle_driver::squareRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_driver::squareRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 s\n"
;
  }

  static const char* value(const ::turtle_driver::squareRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_driver::squareRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct squareRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_driver::squareRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_driver::squareRequest_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_DRIVER_MESSAGE_SQUAREREQUEST_H
