(cl:defpackage turtle_driver-srv
  (:use )
  (:export
   "CIRCLE"
   "<CIRCLE-REQUEST>"
   "CIRCLE-REQUEST"
   "<CIRCLE-RESPONSE>"
   "CIRCLE-RESPONSE"
   "CUSTOM"
   "<CUSTOM-REQUEST>"
   "CUSTOM-REQUEST"
   "<CUSTOM-RESPONSE>"
   "CUSTOM-RESPONSE"
   "SQUARE"
   "<SQUARE-REQUEST>"
   "SQUARE-REQUEST"
   "<SQUARE-RESPONSE>"
   "SQUARE-RESPONSE"
  ))

